# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Akash Narayan/project_22/project_22.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Akash Narayan/project_22/project_22.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{C:/Users/Akash Narayan/project_22/project_22.srcs/sources_1/new/booth_mul.v}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top booth_mul -part xc7a35tcpg236-1


write_checkpoint -force -noxdef booth_mul.dcp

catch { report_utilization -file booth_mul_utilization_synth.rpt -pb booth_mul_utilization_synth.pb }
